targets:
  $default:
    builders:
      source_gen|combining_builder:
        generate_for:
          - lib/**.dart
        options:
          build_extensions:
            '^lib/{{dir}}/{{}}.dart': 'lib/{{dir}}/generated/{{}}.g.dart'